# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    webp:
        generate: true

    filter_sets:
        original: ~
        admin_thumbnail:
            filters:
                thumbnail:
                    size: [150, 150]

        header_image:
            filters:
                # Redimensionnement proportionnel pour une largeur maximale de 1920px
                relative_resize: { widen: 1920 }
                # Compression de qualité pour les images JPEG
                quality: { quality: 85 }
                # Compression de qualité pour les images PNG
                png_compression: { level: 6 }
