# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    
    # Configure webp format
    webp:
        generate: true

    filter_sets:
        original: ~
        admin_thumbnail:
            filters:
                thumbnail:
                    size: [150, 150]
                    mode: outbound

        header_thumbnail:
            filters:
                thumbnail:
                    size: [1080, 608] # Largeur et hauteur souhaitées
                    mode: inset
                    options:
                        jpeg_quality: 85
                        png_compression_level: 8
                        webp_quality: 85

        navbar_logo_thumbnail:
            filters:
                relative_resize:
                    widen: 731

        # Taille de l'image des produits miniatures
        product_thumbnail:
            filters:
                thumbnail:
                    size: [50, 50] # Largeur et hauteur souhaitées pour les produits
                    mode: inset
                    options:
                        jpeg_quality: 85
                        png_compression_level: 8
                        webp_quality: 85
                        interlace: plane

        # Taille de l'image des produits
        product_image:
            filters:
                thumbnail:
                    size: [800, 800] # Largeur et hauteur souhaitées pour les produits
                    mode: outbound
                    options:
                        jpeg_quality: 85
                        png_compression_level: 8
                        webp_quality: 85


        # Taille de la card des produits
        product_card_thumbnail:
            filters:
                thumbnail:
                    size: [340, 500] # Largeur et hauteur souhaitées pour les produits
                    mode: outbound
                    options:
                        jpeg_quality: 85
                        png_compression_level: 8
                        webp_quality: 85

        header_large:
            filters:
                thumbnail:
                    size: [1600, 900]
                    mode: inset
                    options:
                        jpeg_quality: 85
                        png_compression_level: 8
                        webp_quality: 85

        header_medium:
            filters:
                thumbnail:
                    size: [1024, 576]
                    mode: inset
                    options:
                            jpeg_quality: 85
                            png_compression_level: 8
                            webp_quality: 85

        header_small:
            filters:
                thumbnail:
                    size: [768, 432]
                    mode: inset
                    options:
                            jpeg_quality: 85
                            png_compression_level: 8
                            webp_quality: 85

        header_default:
            filters:
                thumbnail:
                    size: [480, 270]
                    mode: inset
                    options:
                            jpeg_quality: 85
                            png_compression_level: 8
                            webp_quality: 85

        sleeve_thumbnail:
            filters:
                thumbnail:
                    size: [32, 32] # Largeur et hauteur souhaitées pour l'image des manches
                    mode: inset
                    options:
                        jpeg_quality: 85
                        png_compression_level: 8
                        webp_quality: 85


