# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    # Configure webp format
    webp:
        generate: true

    filter_sets:
        original: ~
        admin_thumbnail:
            filters:
                thumbnail:
                    size: [150, 150]
                    mode: outbound

        header_thumbnail:
            filters:
                thumbnail:
                    size: [1080, 608] # Largeur et hauteur souhaitées
                    mode: inset
                    options:
                        jpeg_quality: 85
                        png_compression_level: 8
                        webp_quality: 85

        navbar_logo_thumbnail:
            filters:
                relative_resize:
                    widen: 731

        # Taille de l'image des produits miniatures
        product_thumbnail:
            filters:
                thumbnail:
                    size: [96, 96] # Largeur et hauteur souhaitées pour les produits
                    mode: outbound
                    options:
                        jpeg_quality: 85
                        png_compression_level: 8
                        webp_quality: 85
                        interlace: plane

        # Taille de l'image des produits dans détails
        product_image:
            filters:
                thumbnail:
                    size: [800, 800] # Largeur et hauteur souhaitées pour les produits
                    mode: outbound
                    options:
                        jpeg_quality: 85
                        png_compression_level: 8
                        webp_quality: 85

        product_card_thumbnail:
            filters:
                thumbnail:
                    size: [460, 683] # Largeur et hauteur souhaitées pour les cartes produits
                    mode: outbound
                    options:
                        jpeg_quality: 85
                        png_compression_level: 8
                        webp_quality: 85

        sleeve_thumbnail:
            filters:
                thumbnail:
                    size: [50, 50] # Largeur et hauteur souhaitées pour les options de manches
                    mode: inset
                    options:
                        jpeg_quality: 85
                        png_compression_level: 8
                        webp_quality: 85