vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        products:
            uri_prefix: /uploads/images/products
            upload_destination: '%kernel.project_dir%/public/uploads/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        header_image:
            uri_prefix: /uploads/images/headers
            upload_destination: '%kernel.project_dir%/public/uploads/images/headers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
